---
title: "ENVS193DS final"
author: Sophie Pardehpoosh
date: "2026-03-13"
format:
  html:
    toc: true # use this to display a table of contents
execute:
  message: false # make sure messages don't show up
  warning: false # make sure warnings don't show up
---

## [Github repository](https://github.com/spardehpoosh/ENVS-193DS_winter-2026_final.git)

# Set up

```{r}
#| label: reading in packages and data
#| message: false

library(tidyverse) # general use
library(janitor) # cleaning data frames
library(here) # file/folder organization
library(readxl) # reading .xlsx files

# reading in data
kelp <- read_csv(here("data", "kelp_data.csv")) # storing kelp data as an object called kelp for problem 2
```


# Problem 1. Research Writing 

## a. Transparent statistical methods

In part 1, my coworker used simple linear regression to determine whether or not precipitation predicts flooded wetland area. It is "simple" since there is one predictor. 

In part 2, they used a Kruskal-Wallis test to determine whether medians differed accross water year clasification. Since they were comparing more than two predictors they would use ANOVA but since they are comparing medians rather than means, they need the non parametric version which is Kruskal Wallis. 


## b. Figure needed

I would suggest that my coworkers includes a box plot comparing median flooded wetland area across the five water year classifications. The y-axis would have the flooded wetland area (m^2^), while the x axis would label the five water classifications. There would be five boxes on the plot. Each of the five would have a line for the median, with upper and lower quartiles at the top and bottom of the box. Individual data points would be layed on top of the box plots to visualize the raw data. 

## c. Suggestions for rewriting

Flooded wetland area did not change with precipitation (linear regression, F(DF, DF) = test statistic, R^2^ = coefficient of determination, p = 0.11, $\alpha$ = significance level). 
We found no difference in median flooded wetland area between water year classification (wet, above normal, below normal, dry, critical drought) (Kruskal-Wallis test, $\chi$^2^(df) = test statistic, p = 0.12, $\alpha$ = significance level).








